Здесь функция run возвращает пустой интерфейс с типом myError и значением nil 
Поэтому проверку на nil он не проходит 
